### PR TITLE
Add some more of the Elk arming modes

### PR DESCRIPTION
**Pull request by gwww**

### CODE REVIEW

**Comment by BioSehnsucht** [comment]
Have you tested this on the regular HASS UI ? Does it let you disarm from the other arm states, or does it not show the disarm button because the states aren't part of the HASS defined states?

Oops, I see https://github.com/home-assistant/architecture/issues/56 where this might be a problem.

**Comment by gwww** [comment]
My thinking is that we should always "do the right thing" even if the platform cannot, meaning support additional arm modes in the code.

I am really confused about the platform right now, as you've seen in the architecture issue I've raised. The platform supports extensibility in being able to support new service calls. However it is fixed in its ability to support new states. That seems like a conflict in goals.

**Comment by BioSehnsucht** [comment]
I think I want to merge the current branch to master first, then set up a new branch for this functionality and bring the PR into it, and add a (hopefully temporary) config option to toggle whether to use the custom states (your code) or not (my old code). The service calls can always be there, but just give option to change the states used so if using default UI we need to be compatible with it, otherwise the other states should work.

**Comment by BioSehnsucht** [comment]
Merging this into new branch new-arming-modes which I will then add the special sauce to toggle between the old (stock HASS UI compatible) and new (not) functionality, before eventually merging that to master after it's been tested.

Consider gwww-elkm1-lib branch deprecated, though I haven't removed it yet. I have merged gwww-elkm1-lib into master.

**Pull request merged**
